modLoader="javafml"
loaderVersion="[36,)" 
license="All Rights Reserved"
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/"

[[mods]] 
modId="pixelmonbattleconfig" 
version="${file.jarVersion}" 
displayName="Pixelmon Battle Config" 
#updateJSONURL=""
#displayURL="" 
logoFile="pbc_logo.png"
credits="RDM Studios" 
authors="RDM Studios" 
description='''
Simple Pixelmon addon that adds extra config options to Pixelmon.
'''

# Base
[[dependencies.pixelmonbattleconfig]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.pixelmonbattleconfig]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"

# Libraries
[[dependencies.pixelmonbattleconfig]]
    modId="pixelmon"
    mandatory=true
    versionRange="[9.1.3,)"
    ordering="NONE"
    side="BOTH"

# Extras
[[dependencies.pixelmonbattleconfig]]
    modId="jei"
    mandatory=false
    versionRange="[7.7.1.152,]"
    ordering="AFTER"
    side="BOTH"

[[dependencies.pixelmonbattleconfig]]
    modId="jeresources"
    mandatory=false
    versionRange="[0.12,]"
    ordering="AFTER"
    side="BOTH"
	
[[dependencies.pixelmonbattleconfig]]
    modId="jeed"
    mandatory=false
    versionRange="[1.16.5-1.6,]"
    ordering="AFTER"
    side="BOTH"

[[dependencies.pixelmonbattleconfig]]
    modId="theoneprobe"
    mandatory=false
    versionRange="[1.16-3.1.7,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.pixelmonbattleconfig]]
    modId="datafixerslayer"
    mandatory=false
    versionRange="[1.0-3,]"
    ordering="AFTER"
    side="BOTH"

[[dependencies.pixelmonbattleconfig]]
    modId="appleskin"
    mandatory=false
    versionRange="[mc1.16.5-2.4.0,]"
    ordering="AFTER"
    side="CLIENT"

[[dependencies.pixelmonbattleconfig]]
    modId="configured"
    mandatory=false
    versionRange="[1.5.3,]"
    ordering="AFTER"
    side="CLIENT"

[[dependencies.pixelmonbattleconfig]]
    modId="catalogue"
    mandatory=false
    versionRange="[1.6.1,]"
    ordering="AFTER"
    side="CLIENT"